from __future__ import annotations
from typing import Protocol

class TelemetryBackend(Protocol):
    name: str
    available: bool
    def start(self) -> bool: ...
    def stop(self) -> None: ...
    def status(self) -> dict: ...

class NotificationBackend(Protocol):
    def notify(self, title: str, message: str, *, level: str = "info") -> bool: ...

class AnalystBackend(Protocol):
    def health(self, timeout: float = 2.0) -> dict: ...
    def explain(self, payload: dict, timeout: float = 8.0) -> str | None: ...
